out_dir: /nobackup/users/junhong/Logs/results
metric_best: accuracy
seed: 42
wandb:
  use: True
  project: unifiedGT
dataset:
  dir: /nobackup/users/junhong/Data
  format: PyG-Pokec
  name: Pokec
  task: hetero_node
  task_type: classification
  task_entity: user
  transductive: True
  node_encoder: True
  node_encoder_name: Raw
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: none
  edge_encoder_bn: False
num_threads: 24
num_workers: 18
train:
  mode: custom
  sampler: hgt
  neighbor_sizes_dict: >
    "{'user': [2048, 2048, 512, 512],\
     'life_style': [128, 128, 128],\
     'music': [128, 128, 128],\
     'cars': [128, 128, 128],\
     'politics': [128, 128, 128],\
     'relationships': [128, 128, 128],\
     'art_culture': [128, 128, 128],\
     'hobbies_interests': [128, 128, 128],\
     'science_technologies': [128, 128, 128],\
     'computers_internet': [128, 128, 128],\
     'education': [128, 128, 128],\
     'sport': [128, 128, 128],\
     'movies': [128, 128, 128],\
     'travelling': [128, 128, 128],\
     'health': [128, 128, 128],\
     'companies_brands': [128, 128, 128]\
    }"
  iter_per_epoch: 256
  batch_size: 32
  eval_period: 4
  ckpt_period: 100
  tqdm: True
  persistent_workers: True
  pin_memory: True
val:
  sampler: hgt
  iter_per_epoch: 512
  tqdm: True
model:
  type: HomoGNNModel
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gnn:
  layer_type: APPNP
  K: 3
  alpha: 0.1
  layers_pre_mp: 2
  layers_post_mp: 1  
  dim_inner: 256  
  batch_norm: True
  layer_norm: False
  act: relu
  input_dropout: 0.0
  dropout: 0.5
  agg: mean
  use_linear: False
optim:
  batch_accumulation: 8
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 500
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
#optim:
#  clip_grad_norm: True
#  optimizer: adamW
#  weight_decay: 1e-5
#  base_lr: 0.0001
#  max_epoch: 100
#  scheduler: reduce_on_plateau
#  reduce_factor: 0.5
#  schedule_patience: 5
#  min_lr: 1e-6
