out_dir: /nobackup/users/junhong/Logs/results/Pokec
metric_best: accuracy
seed: 42
wandb:
  use: True
  project: unifiedGT
dataset:
  dir: /nobackup/users/junhong/Data
  format: PyG-Pokec
  name: Pokec
  task: hetero_node
  task_type: classification
  task_entity: user
  transductive: True
  node_encoder: True
  node_encoder_name: Hetero_Raw+Hetero_Label+Hetero_Metapath
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: none
  edge_encoder_bn: False
posenc_Hetero_Label:
  enable: True
  dim_pe: 0
posenc_Hetero_Metapath:
  enable: True
  layers: 1
  dim_pe: 128
num_threads: 24
num_workers: 18
train:
  mode: custom
  sampler: hgt
  neighbor_sizes_dict: >
    "{'user': [2048, 2048, 512, 512],\
     'life_style': [128, 128, 128],\
     'music': [128, 128, 128],\
     'cars': [128, 128, 128],\
     'politics': [128, 128, 128],\
     'relationships': [128, 128, 128],\
     'art_culture': [128, 128, 128],\
     'hobbies_interests': [128, 128, 128],\
     'science_technologies': [128, 128, 128],\
     'computers_internet': [128, 128, 128],\
     'education': [128, 128, 128],\
     'sport': [128, 128, 128],\
     'movies': [128, 128, 128],\
     'travelling': [128, 128, 128],\
     'health': [128, 128, 128],\
     'companies_brands': [128, 128, 128]\
    }"
  iter_per_epoch: 256
  batch_size: 32
  eval_period: 4
  ckpt_period: 100
  tqdm: True
  persistent_workers: True
  pin_memory: True
val:
  sampler: hgt
  iter_per_epoch: 256
  tqdm: True
model:
  type: GTModel
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gt:
  layer_type: SparseNodeTransformer
  layers_pre_gt: 1
  layers: 3
  layers_post_gt: 1
  attn_heads: 8
  dim_hidden: 256  
  dropout: 0.5     # global transformer dropout
  attn_dropout: 0.2
  batch_norm: False
  layer_norm: True
  act: relu
  attn_mask: Edge
  residual: Fixed
  ffn: Type
gnn:
  dropout: 0.0
optim:
  batch_accumulation: 32
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0005
  max_epoch: 500
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
#optim:
#  clip_grad_norm: True
#  optimizer: adamW
#  weight_decay: 1e-5
#  base_lr: 0.0001
#  max_epoch: 100
#  scheduler: reduce_on_plateau
#  reduce_factor: 0.5
#  schedule_patience: 5
#  min_lr: 1e-6
