out_dir: /nobackup/users/junhong/Logs/results
metric_best: f1
seed: 42
wandb:
  use: True
  project: H2GB
dataset:
  dir: /nobackup/users/junhong/Data
  format: PyG-RCDD
  name: RCDD
  task: hetero_node
  task_type: classification
  task_entity: item
  transductive: True
  node_encoder: True
  node_encoder_name: Hetero_Raw
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: none
  edge_encoder_bn: False
num_threads: 24
num_workers: 18
train:
  mode: custom
  sampler: nag
  batch_size: 1000
  eval_period: 2
  ckpt_period: 100
  tqdm: True
  persistent_workers: True
  pin_memory: True
val:
  sampler: nag
  iter_per_epoch: 256
  tqdm: True
model:
  type: NAGphormerModel
  loss_fun: weighted_cross_entropy
  loss_fun_weight: [1, 1] # Shut off the auto class weight
  edge_decoding: dot
  graph_pooling: mean
gnn:
  hops: 5
  layers_mp: 3
  attn_heads: 8
  layers_pre_mp: 0
  layers_post_mp: 1  # Not used when `gnn.head: san_graph`
  dim_inner: 256  # `gt.dim_hidden` must match `gnn.dim_inner`
  batch_norm: True
  layer_norm: False
  act: relu
  input_dropout: 0.0
  dropout: 0.2
  agg: mean
  use_linear: False
optim:
  batch_accumulation: 1
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 500
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
#optim:
#  clip_grad_norm: True
#  optimizer: adamW
#  weight_decay: 1e-5
#  base_lr: 0.0001
#  max_epoch: 100
#  scheduler: reduce_on_plateau
#  reduce_factor: 0.5
#  schedule_patience: 5
#  min_lr: 1e-6
