out_dir: ./results/RCDD
metric_best: f1
seed: 42
wandb:
  use: True
  project: h2gb
dataset:
  dir: ./data
  format: PyG-RCDD
  name: RCDD
  task: hetero_node
  task_type: classification
  task_entity: item
  transductive: True
  node_encoder: True
  node_encoder_name: Raw
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: none
  edge_encoder_bn: False
num_threads: 24
num_workers: 18
train:
  mode: custom
  sampler: hgt
  neighbor_sizes: [256, 256, 256, 256] # 256 * 4
  iter_per_epoch: 256
  batch_size: 32
  eval_period: 4
  ckpt_period: 100
  tqdm: True
  persistent_workers: True
  pin_memory: True
val:
  sampler: hgt
  iter_per_epoch: 256
  tqdm: True
model:
  type: ACMGCNModel
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gnn:
  layer_type: acmgcn
  layers_mp: 3
  dim_inner: 256
  dropout: 0.5
optim:
  batch_accumulation: 1
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 500
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
#optim:
#  clip_grad_norm: True
#  optimizer: adamW
#  weight_decay: 1e-5
#  base_lr: 0.0001
#  max_epoch: 100
#  scheduler: reduce_on_plateau
#  reduce_factor: 0.5
#  schedule_patience: 5
#  min_lr: 1e-6
