out_dir: /nobackup/users/junhong/Logs/results/IEEE-CIS
metric_best: f1
seed: 42
wandb:
  use: True
  project: unifiedGT
dataset:
  dir: /nobackup/users/junhong/Data
  format: IEEE-CIS
  name: IEEE-CIS
  task: hetero_node
  task_type: classification
  task_entity: transaction
  transductive: True
  node_encoder: True
  node_encoder_name: Raw
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: none
  edge_encoder_bn: False
posenc_Hetero_Node2Vec:
  enable: True
  layers: 1
  dim_pe: 64
num_threads: 24
num_workers: 18
train:
  mode: custom
  sampler: goat
  neighbor_sizes: [20,10,5]
  iter_per_epoch: 256
  batch_size: 32
  eval_period: 4
  ckpt_period: 100
  tqdm: True
  persistent_workers: True
  pin_memory: True
val:
  sampler: goat
  iter_per_epoch: 256
  tqdm: True
model:
  type: GOATModel
  loss_fun: weighted_cross_entropy
  loss_fun_weight: [1, 5]
  edge_decoding: dot
  graph_pooling: mean
gnn:
  layer_type: full
  layers_mp: 3
  attn_heads: 8
  layers_pre_mp: 0
  layers_post_mp: 1  
  dim_inner: 64  
  batch_norm: True
  layer_norm: False
  act: relu
  dropout: 0.5
  attn_dropout: 0.2
optim:
  batch_accumulation: 32
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0005
  max_epoch: 500
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
#optim:
#  clip_grad_norm: True
#  optimizer: adamW
#  weight_decay: 1e-5
#  base_lr: 0.0001
#  max_epoch: 100
#  scheduler: reduce_on_plateau
#  reduce_factor: 0.5
#  schedule_patience: 5
#  min_lr: 1e-6
