out_dir: ./results/IEEE-CIS
metric_best: f1
seed: 42
wandb:
  use: True
  project: h2gb
dataset:
  dir: ./data
  format: IEEE-CIS
  name: IEEE-CIS
  task: hetero_node
  task_type: classification
  task_entity: transaction
  transductive: True
  node_encoder: True
  node_encoder_name: Hetero_Raw
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: none
  edge_encoder_bn: False
num_threads: 24
num_workers: 18
train:
  mode: custom
  sampler: full_batch
  tqdm: True
  persistent_workers: True
  pin_memory: True
val:
  sampler: full_batch
  iter_per_epoch: 256
  tqdm: True
model:
  type: LPModel
  loss_fun: weighted_cross_entropy
  loss_fun_weight: [1, 5]
  edge_decoding: dot
  graph_pooling: mean
gnn:
  alpha: 0.1
  hops: 1
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 1
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
#optim:
#  clip_grad_norm: True
#  optimizer: adamW
#  weight_decay: 1e-5
#  base_lr: 0.0001
#  max_epoch: 100
#  scheduler: reduce_on_plateau
#  reduce_factor: 0.5
#  schedule_patience: 5
#  min_lr: 1e-6
