out_dir: /nobackup/users/junhong/Logs/results
metric_best: accuracy
seed: 42
wandb:
  use: True
  project: H2GB
dataset:
  dir: /nobackup/users/junhong/Data
  format: PyG-OAG
  name: chemistry
  task: hetero_node
  task_type: classification
  task_entity: paper
  transductive: True
  node_encoder: True
  node_encoder_name: Hetero_Raw+Hetero_Metapath
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: none
  edge_encoder_bn: False
posenc_Hetero_Metapath:
  enable: True
  layers: 1
  dim_pe: 128
num_threads: 24
num_workers: 18
train:
  mode: custom
  sampler: hgt
  neighbor_sizes: [64, 64, 64, 64, 64, 64] # 64 * 6
  iter_per_epoch: 256
  batch_size: 32
  eval_period: 2
  ckpt_period: 100
  tqdm: True
val:
  sampler: hgt
  iter_per_epoch: 128
  tqdm: True
model:
  type: MLPModel
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gnn:
  layers_pre_mp: 0
  layers_post_mp: 2  # Not used when `gnn.head: san_graph`
  dim_inner: 256  # `gt.dim_hidden` must match `gnn.dim_inner`
  act: relu
  input_dropout: 0.0
  dropout: 0.2  # local MP-GNN dropout
  agg: mean
optim:
  batch_accumulation: 1
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 500
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
#optim:
#  clip_grad_norm: True
#  optimizer: adamW
#  weight_decay: 1e-5
#  base_lr: 0.0001
#  max_epoch: 100
#  scheduler: reduce_on_plateau
#  reduce_factor: 0.5
#  schedule_patience: 5
#  min_lr: 1e-6
